version: '3'
networks:
  app-network:
services:
  pg-db:
    image: postgres:11
    logging:
      driver: json-file
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - .:/app
